language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../sophieparshina-labs-381706-2
  - make -j
  - ./List/List
  - ./ListTest/ListTest
notifications:
  email: false
