language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../sophieparshina-labs-master-381706-2
  - make -j
  - ./List/List
  - ./ListTest/ListTest
  - ./Stack/Stack
  - ./StackTest/StackTest
notifications:
  email: false
